"""Criando tabela chamados

Revision ID: 2140ab9ed3c2
Revises: 
Create Date: 2026-08-04 16:07:20.529969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2140ab9ed3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados',
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('equipamento', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('prioridade', sa.String(length=30), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('data_abertura', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamados')
    # ### end Alembic commands ###
